//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMNAVIGATIONOBJECTS_COMMPLANNERGOALS_H_
#define COMMNAVIGATIONOBJECTS_COMMPLANNERGOALS_H_

#include "CommNavigationObjects/CommPlannerGoalsCore.hh"

namespace CommNavigationObjects {
		
class CommPlannerGoals : public CommPlannerGoalsCore {
	public:
		// default constructors
		CommPlannerGoals();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommPlannerGoals(const std::vector<CommNavigationObjects::CommPlannerGoal> &goals);
		
		CommPlannerGoals(const CommPlannerGoalsCore &commPlannerGoals);
		CommPlannerGoals(const DATATYPE &commPlannerGoals);
		virtual ~CommPlannerGoals();
		
		// use framework specific getter and setter methods from core (base) class
		using CommPlannerGoalsCore::get;
		using CommPlannerGoalsCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommPlannerGoals &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommNavigationObjects */
#endif /* COMMNAVIGATIONOBJECTS_COMMPLANNERGOALS_H_ */
