//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMNAVIGATIONOBJECTS_DISTANCETOGOAL_H_
#define COMMNAVIGATIONOBJECTS_DISTANCETOGOAL_H_

#include "CommNavigationObjects/DistanceToGoalCore.hh"

namespace CommNavigationObjects {
		
class DistanceToGoal : public DistanceToGoalCore {
	public:
		// default constructors
		DistanceToGoal();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// DistanceToGoal(const double &l1, const double &l2);
		
		DistanceToGoal(const DistanceToGoalCore &distanceToGoal);
		DistanceToGoal(const DATATYPE &distanceToGoal);
		virtual ~DistanceToGoal();
		
		// use framework specific getter and setter methods from core (base) class
		using DistanceToGoalCore::get;
		using DistanceToGoalCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const DistanceToGoal &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommNavigationObjects */
#endif /* COMMNAVIGATIONOBJECTS_DISTANCETOGOAL_H_ */
