//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINSPEECH_COMMOBJECTDROPOUTPUTMESSAGE_H_
#define DOMAINSPEECH_COMMOBJECTDROPOUTPUTMESSAGE_H_

#include "DomainSpeech/CommObjectDropOutputMessageCore.hh"

namespace DomainSpeech {
		
class CommObjectDropOutputMessage : public CommObjectDropOutputMessageCore {
	public:
		// default constructors
		CommObjectDropOutputMessage();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommObjectDropOutputMessage(const int &obj_carried_index);
		
		CommObjectDropOutputMessage(const CommObjectDropOutputMessageCore &commObjectDropOutputMessage);
		CommObjectDropOutputMessage(const DATATYPE &commObjectDropOutputMessage);
		virtual ~CommObjectDropOutputMessage();
		
		// use framework specific getter and setter methods from core (base) class
		using CommObjectDropOutputMessageCore::get;
		using CommObjectDropOutputMessageCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommObjectDropOutputMessage &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace DomainSpeech */
#endif /* DOMAINSPEECH_COMMOBJECTDROPOUTPUTMESSAGE_H_ */
