//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINSPEECH_COMMOBJECTPLACEMENTOUTPUTMESSAGE_H_
#define DOMAINSPEECH_COMMOBJECTPLACEMENTOUTPUTMESSAGE_H_

#include "DomainSpeech/CommObjectPlacementOutputMessageCore.hh"

namespace DomainSpeech {
		
class CommObjectPlacementOutputMessage : public CommObjectPlacementOutputMessageCore {
	public:
		// default constructors
		CommObjectPlacementOutputMessage();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommObjectPlacementOutputMessage(const std::string &objectType, const std::vector<double> &objectSize, const double &objectMass);
		
		CommObjectPlacementOutputMessage(const CommObjectPlacementOutputMessageCore &commObjectPlacementOutputMessage);
		CommObjectPlacementOutputMessage(const DATATYPE &commObjectPlacementOutputMessage);
		virtual ~CommObjectPlacementOutputMessage();
		
		// use framework specific getter and setter methods from core (base) class
		using CommObjectPlacementOutputMessageCore::get;
		using CommObjectPlacementOutputMessageCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommObjectPlacementOutputMessage &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace DomainSpeech */
#endif /* DOMAINSPEECH_COMMOBJECTPLACEMENTOUTPUTMESSAGE_H_ */
