//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMOBJECTRECOGNITIONOBJECTS_COMMPEOPLE_H_
#define COMMOBJECTRECOGNITIONOBJECTS_COMMPEOPLE_H_

#include "CommObjectRecognitionObjects/CommPeopleCore.hh"

namespace CommObjectRecognitionObjects {
		
class CommPeople : public CommPeopleCore {
	public:
		// default constructors
		CommPeople();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommPeople(const std::vector<CommObjectRecognitionObjects::CommPerson> &people, const bool &is_valid = false);
		
		CommPeople(const CommPeopleCore &commPeople);
		CommPeople(const DATATYPE &commPeople);
		virtual ~CommPeople();
		
		// use framework specific getter and setter methods from core (base) class
		using CommPeopleCore::get;
		using CommPeopleCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommPeople &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommObjectRecognitionObjects */
#endif /* COMMOBJECTRECOGNITIONOBJECTS_COMMPEOPLE_H_ */
