//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------

#include "CommObjectRecognitionObjects/CommPerson.hh"

using namespace CommObjectRecognitionObjects;

CommPerson::CommPerson()
:	CommPersonCore()
{  }


/**
 * Constructor to set all values.
 * NOTE that you have to keep this constructor consistent with the model!
 * Use  at your own choice.
 *
 * The preferred way to set values for initialization is:
 *      CommRepository::MyCommObject obj;
 *      obj.setX(1).setY(2).setZ(3)...;
CommPerson::CommPerson(const int &id, const std::string &name, const std::vector<std::string> &data_names, const std::vector<double> &data_numbers)
:	CommPersonCore() // base constructor sets default values as defined in the model
{
	setId(id);
	setName(name);
	setData_names(data_names);
	setData_numbers(data_numbers);
}
 */

CommPerson::CommPerson(const CommPersonCore &commPerson)
:	CommPersonCore(commPerson)
{  }

CommPerson::CommPerson(const DATATYPE &commPerson)
:	CommPersonCore(commPerson)
{  }

CommPerson::~CommPerson()
{  }
