//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMOBJECTRECOGNITIONOBJECTS_COMMOBJECTRECOGNITIONEVENTBUMPRESULT_H_
#define COMMOBJECTRECOGNITIONOBJECTS_COMMOBJECTRECOGNITIONEVENTBUMPRESULT_H_

#include "CommObjectRecognitionObjects/CommObjectRecognitionEventBumpResultCore.hh"

namespace CommObjectRecognitionObjects {
		
class CommObjectRecognitionEventBumpResult : public CommObjectRecognitionEventBumpResultCore {
	public:
		// default constructors
		CommObjectRecognitionEventBumpResult();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommObjectRecognitionEventBumpResult(const CommObjectRecognitionObjects::ObjectRecognitionState &state, const std::vector<unsigned int> &object_id, const unsigned int &environment_id = 0);
		
		CommObjectRecognitionEventBumpResult(const CommObjectRecognitionEventBumpResultCore &commObjectRecognitionEventBumpResult);
		CommObjectRecognitionEventBumpResult(const DATATYPE &commObjectRecognitionEventBumpResult);
		virtual ~CommObjectRecognitionEventBumpResult();
		
		// use framework specific getter and setter methods from core (base) class
		using CommObjectRecognitionEventBumpResultCore::get;
		using CommObjectRecognitionEventBumpResultCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommObjectRecognitionEventBumpResult &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommObjectRecognitionObjects */
#endif /* COMMOBJECTRECOGNITIONOBJECTS_COMMOBJECTRECOGNITIONEVENTBUMPRESULT_H_ */
