//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMOBJECTRECOGNITIONOBJECTS_COMMPERSON_H_
#define COMMOBJECTRECOGNITIONOBJECTS_COMMPERSON_H_

#include "CommObjectRecognitionObjects/CommPersonCore.hh"

namespace CommObjectRecognitionObjects {
		
class CommPerson : public CommPersonCore {
	public:
		// default constructors
		CommPerson();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommPerson(const int &id, const std::string &name, const std::vector<std::string> &data_names, const std::vector<double> &data_numbers);
		
		CommPerson(const CommPersonCore &commPerson);
		CommPerson(const DATATYPE &commPerson);
		virtual ~CommPerson();
		
		// use framework specific getter and setter methods from core (base) class
		using CommPersonCore::get;
		using CommPersonCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommPerson &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommObjectRecognitionObjects */
#endif /* COMMOBJECTRECOGNITIONOBJECTS_COMMPERSON_H_ */
